version: '3.8'

services:
  web:
    image: proj-act-cohesio
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      - OAUTH_REDIRECT_URI=http://localhost/Controlador/llista.php
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSW=cohesio
      - DB_NAME=activitats_cohesio

  db:
    image: mariadb:10.2
    environment:
      - MARIADB_ROOT_PASSWORD=cohesio
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docs/activitats_cohesio.sql:/docker-entrypoint-initdb.d/activitats_cohesio.sql
    ports:
      - 3306:3306
